# code: language=ansible
---
# tasks file for k3s
- name: Update OS
  ansible.builtin.apt:
    upgrade: "dist"
    update_cache: true
    cache_valid_time: 3600

- name: Set Default Editor to vim
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim
    state: selected

- name: Check Reboot Status
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: reboot
  changed_when: reboot.stat.exists
  notify: Perform Reboot

- name: Configure Network Interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: "/etc/network/interfaces"
    owner: "root"
    group: "root"
    mode: '0644'
  notify: Perform Reboot

- name: Download k3s binary x64
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"

- name: Execute Master Tasks
  ansible.builtin.include_tasks: k3s-master.yaml
  when: ansible_fqdn == master_node
- name: Execute Node Tasks
  ansible.builtin.include_tasks: k3s-node.yaml
  when: ansible_fqdn != master_node
