# code: language=ansible
---
# tasks file for debian-init
- name: Ensure user
  ansible.builtin.user:
    name: "{{ user.username }}"
    comment: "{{ user.fullname }}"
- name: Try to set ZSH as Default Shell
  block:
    - name: Check for ZSH
      ansible.builtin.command: zsh --version
      register: zsh_check
      check_mode: false
      changed_when: false
      failed_when: zsh_check.rc != 0 and zsh_check.rc != 127
    - name: Set User's Shell to ZSH
      ansible.builtin.user:
        name: "{{ user.username }}"
        shell: /bin/zsh
  rescue:
    - name: Set User's Shell to Bash
      ansible.builtin.user:
        name: "{{ user.username }}"
        shell: /bin/bash

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ user.username }}/.ssh"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: '0755'
- name: Ensure authorized_keys are configured
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "/home/{{ user.username }}/.ssh/authorized_keys"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: '0644'
